version: '3'

services:

  redis:
   image: "redis:alpine"
   ports:
      - "6379:6379"
   command: ["redis-server"]
   hostname: redis


  db-task-manager:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dyna
      MYSQL_DATABASE: task-manager
      MYSQL_USER: task
      MYSQL_PASSWORD: manager
      TZ: UTC
    ports:
      - "3316:3306"
      
  
 
    
    

 
                 


 
